-- Idempotent seed data for development/testing

-- Seed: categories (authoritative taxonomy)
INSERT INTO categories (name, slug) VALUES
  ('Rekrutacja i selekcja', 'rekrutacja-selekcja'),
  ('Onboarding', 'onboarding'),
  ('Offboarding', 'offboarding'),
  ('Szkolenia i rozwój (L&D)', 'szkolenia-rozwoj'),
  ('Ocena wyników i feedback', 'ocena-wynikow-feedback'),
  ('Zarządzanie talentami i sukcesja', 'talent-sukcesja'),
  ('Wynagrodzenia i benefity', 'wynagrodzenia-benefity'),
  ('Prawo pracy i compliance (RODO/BHP)', 'prawo-pracy-compliance'),
  ('Relacje z pracownikami', 'employee-relations'),
  ('Kultura organizacyjna i zaangażowanie', 'kultura-zaangazowanie'),
  ('Różnorodność i inkluzja (D&I)', 'diversity-inclusion'),
  ('Well-being i BHP', 'wellbeing-bhp'),
  ('HR Analytics i metryki', 'hr-analytics')
ON CONFLICT (slug) DO NOTHING;

-- Seed: tags (starter set)
INSERT INTO tags (name, slug) VALUES
  -- Rekrutacja i selekcja
  ('rekrutacja', 'rekrutacja'),
  ('selekcja', 'selekcja'),
  ('sourcing', 'sourcing'),
  ('ATS', 'ats'),
  ('job description', 'job-description'),
  ('rozmowa kwalifikacyjna', 'rozmowa-kwalifikacyjna'),
  ('candidate experience', 'candidate-experience'),
  ('talent acquisition', 'talent-acquisition'),
  ('rekrutacja międzynarodowa', 'rekrutacja-miedzynarodowa'),
  ('rekrutacja inkluzywna', 'rekrutacja-inkluzywna'),
  ('AI', 'ai'),
  ('LinkedIn', 'linkedin'),
  ('GitHub', 'github'),
  ('boolean search', 'boolean-search'),
  ('talent pools', 'talent-pools'),
  ('copywriting', 'copywriting'),
  ('A/B testing', 'ab-testing'),
  ('personalizacja', 'personalizacja'),
  ('behawioralne', 'behawioralne'),
  ('STAR', 'star'),
  ('ocena', 'ocena'),
  ('bias', 'bias'),
  ('globalne zespoły', 'globalne-zespoly'),
  ('cross-cultural', 'cross-cultural'),
  ('relokacja', 'relokacja'),
  ('fintech', 'fintech'),
  ('risk management', 'risk-management'),
  ('highly regulated', 'highly-regulated'),
  ('banking', 'banking'),

  -- Onboarding / Offboarding
  ('onboarding', 'onboarding'),
  ('offboarding', 'offboarding'),
  ('exit interview', 'exit-interview'),
  ('rozmowa wyjściowa', 'rozmowa-wyjściowa'),
  ('checklist', 'checklist'),
  ('dokumenty', 'dokumenty'),
  ('integracja', 'integracja'),
  ('nowy pracownik', 'nowy-pracownik'),
  ('welcome experience', 'welcome-experience'),
  ('pierwsze dni', 'pierwsze-dni'),
  ('alumni', 'alumni'),
  ('knowledge transfer', 'knowledge-transfer'),
  ('retencja', 'retencja'),
  ('analiza', 'analiza'),

  -- L&D / Ocena
  ('szkolenia', 'szkolenia'),
  ('rozwój', 'rozwoj'),
  ('kompetencje', 'kompetencje'),
  ('reskilling', 'reskilling'),
  ('upskilling', 'upskilling'),
  ('feedback', 'feedback'),
  ('ocena pracownicza', 'ocena-pracownicza'),
  ('L&D', 'ld'),
  ('e-learning', 'e-learning'),
  ('microlearning', 'microlearning'),
  ('blended learning', 'blended-learning'),
  ('360 stopni', '360-stopni'),
  ('continuous feedback', 'continuous-feedback'),
  ('learning culture', 'learning-culture'),
  ('skills-based', 'skills-based'),
  ('agile workforce', 'agile-workforce'),
  ('LMS', 'lms'),
  ('interaktywne', 'interaktywne'),
  ('gamifikacja', 'gamifikacja'),
  ('VR', 'vr'),
  ('krótkie moduły', 'krotkie-moduly'),
  ('nawyki', 'nawyki'),
  ('hybrydowe', 'hybrydowe'),
  ('metody nauki', 'metody-nauki'),
  ('ścieżki', 'sciezki'),
  ('kompetencje przyszłości', 'kompetencje-przyszlosci'),
  ('learning organization', 'learning-organization'),

  -- Talenty i sukcesja
  ('zarządzanie talentami', 'zarzadzanie-talentami'),
  ('plan sukcesji', 'plan-sukcesji'),
  ('talent mapping', 'talent-mapping'),
  ('high potential', 'high-potential'),
  ('mentoring', 'mentoring'),
  ('assessment', 'assessment'),
  ('leadership', 'leadership'),
  ('sukcesja', 'sukcesja'),
  ('talent pipeline', 'talent-pipeline'),
  ('bench strength', 'bench-strength'),
  ('następcy', 'nastepcy'),
  ('menedżerowie', 'menedzerowie'),
  ('9-box', '9-box'),
  ('pipeline', 'pipeline'),
  ('strategia', 'strategia'),
  ('competitive advantage', 'competitive-advantage'),

  -- Wynagrodzenia i benefity
  ('wynagrodzenia', 'wynagrodzenia'),
  ('benefity', 'benefity'),
  ('pay equity', 'pay-equity'),
  ('widełki płacowe', 'widelki-placowe'),
  ('PPK', 'ppk'),
  ('PPE', 'ppe'),
  ('kafeteria', 'kafeteria'),
  ('compensation', 'compensation'),
  ('equity', 'equity'),
  ('stock options', 'stock-options'),
  ('transparentność', 'transparentnosc'),
  ('benchmarking', 'benchmarking'),
  ('struktury płacowe', 'struktury-placowe'),
  ('gender pay gap', 'gender-pay-gap'),
  ('job evaluation', 'job-evaluation'),
  ('emerytura', 'emerytura'),
  ('oszczędzanie', 'oszczedzanie'),
  ('satysfakcja', 'satysfakcja'),
  ('komunikacja', 'komunikacja'),

  -- Prawo pracy i compliance
  ('prawo pracy', 'prawo-pracy'),
  ('RODO', 'rodo'),
  ('BHP', 'bhp'),
  ('czas pracy', 'czas-pracy'),
  ('dyscyplinarka', 'dyscyplinarka'),
  ('umowa o pracę', 'umowa-o-prace'),
  ('zlecenie', 'zlecenie'),
  ('B2B', 'b2b'),
  ('compliance', 'compliance'),
  ('dane osobowe', 'dane-osobowe'),
  ('zgody', 'zgody'),
  ('nadgodziny', 'nadgodziny'),
  ('urlopy', 'urlopy'),
  ('monitoring', 'monitoring'),
  ('mobbing', 'mobbing'),
  ('molestowanie', 'molestowanie'),
  ('równość', 'rownosc'),
  ('dyskryminacja', 'dyskryminacja'),
  ('czas nieokreślony', 'czas-nieokreslony'),
  ('czas określony', 'czas-okreslony'),
  ('okres próbny', 'okres-probny'),
  ('zastępstwo', 'zastepstwo'),
  ('dzieło', 'dzielo'),
  ('umowy cywilnoprawne', 'umowy-cywilnoprawne'),
  ('ruch ciągły', 'ruch-ciagly'),
  ('praca w nocy', 'praca-w-nocy'),
  ('praca w ruchu ciągłym', 'praca-w-ruchu-ciaglym'),
  ('praca w rolnictwie', 'praca-w-rolnictwie'),
  ('praca w transporcie', 'praca-w-transporcie'),
  ('młodociani', 'mlodociani'),
  ('kobiety w ciąży', 'kobiety-w-ciazy'),
  ('niedziele', 'niedziele'),
  ('święta', 'swieta'),
  ('zakazy', 'zakazy'),
  ('dodatki', 'dodatki'),
  ('rekompensaty', 'rekompensaty'),
  ('definicje', 'definicje'),
  ('organizacja', 'organizacja'),
  ('wiek', 'wiek'),
  ('zwolnienia', 'zwolnienia'),
  ('rolnictwo', 'rolnictwo'),
  ('transport', 'transport'),
  ('PIP', 'pip'),
  ('kontrola', 'kontrola'),
  ('inspektorzy', 'inspektorzy'),
  ('uprawnienia', 'uprawnienia'),
  ('odwołania', 'odwolania'),
  ('sądy pracy', 'sady-pracy'),
  ('spory', 'spory'),
  ('dowody', 'dowody'),
  ('wyroki', 'wyroki'),
  ('związki zawodowe', 'zwiazki-zawodowe'),
  ('konsultacje', 'konsultacje'),
  ('negocjacje', 'negocjacje'),
  ('strajki', 'strajki'),
  ('systemy czasu', 'systemy-czasu'),
  ('wypoczynkowy', 'wypoczynkowy'),
  ('na żądanie', 'na-zadanie'),
  ('bezpłatny', 'bezplatny'),
  ('okolicznościowy', 'okolicznosciowy'),
  ('kary porządkowe', 'kary-porzadkowe'),
  ('rozwiązanie umowy', 'rozwiazanie-umowy'),
  ('wypowiedzenie', 'wypowiedzenie'),
  ('porozumienie stron', 'porozumienie-stron'),
  ('bez wypowiedzenia', 'bez-wypowiedzenia'),
  ('okresy', 'okresy'),
  ('prawa pracowników', 'prawa-pracownikow'),
  ('UODO', 'uodo'),
  ('prywatność', 'prywatnosc'),
  ('wizyjny', 'wizyjny'),
  ('komputerowy', 'komputerowy'),
  ('wypadki', 'wypadki'),
  ('awanse', 'awanse'),
  ('ochrona', 'ochrona'),
  ('minimalne', 'minimalne'),
  ('składniki', 'skladniki'),
  ('premie', 'premie'),
  ('umowy', 'umowy'),
  ('obowiązki', 'obowiazki'),
  ('regulacje', 'regulacje'),
  ('ryzyko', 'ryzyko'),
  ('zgodność', 'zgodnosc'),
  ('etyka', 'etyka'),

  -- Relacje z pracownikami
  ('employee relations', 'employee-relations'),
  ('relacje', 'relacje'),
  ('zaufanie', 'zaufanie'),
  ('mediacja', 'mediacja'),
  ('konflikty', 'konflikty'),
  ('klimat', 'klimat'),
  ('retention', 'retention'),
  ('turnover', 'turnover'),
  ('lojalność', 'lojalnosc'),

  -- Kultura organizacyjna i zaangażowanie
  ('kultura organizacyjna', 'kultura-organizacyjna'),
  ('zaangażowanie', 'zaangazowanie'),
  ('komunikacja wewnętrzna', 'komunikacja-wewnetrzna'),
  ('wartości organizacyjne', 'wartosci-organizacyjne'),
  ('engagement', 'engagement'),
  ('employee experience', 'employee-experience'),
  ('employer branding', 'employer-branding'),
  ('employer advocacy', 'employer-advocacy'),
  ('storytelling', 'storytelling'),
  ('internal branding', 'internal-branding'),
  ('culture change', 'culture-change'),
  ('tożsamość', 'tozsamosc'),
  ('living values', 'living-values'),
  ('kultura szacunku', 'kultura-szacunku'),
  ('wartości', 'wartosci'),
  ('employer brand', 'employer-brand'),
  ('ambasadorzy', 'ambasadorzy'),
  ('social media', 'social-media'),
  ('content marketing', 'content-marketing'),
  ('kanały', 'kanaly'),
  ('kultura', 'kultura'),
  ('tradycje', 'tradycje'),
  ('motywacja', 'motywacja'),
  ('biznes', 'biznes'),
  ('partnerstwo', 'partnerstwo'),
  ('wartość', 'wartosc'),

  -- Różnorodność i inkluzja (D&I)
  ('diversity & inclusion', 'diversity-inclusion'),
  ('antydyskryminacja', 'antydyskryminacja'),
  ('inclusive hiring', 'inclusive-hiring'),
  ('unconscious bias', 'unconscious-bias'),
  ('inclusive leadership', 'inclusive-leadership'),
  ('przywództwo', 'przywodztwo'),
  ('coaching', 'coaching'),
  ('inkluzyjność', 'inkluzyjnosc'),
  ('świadomość', 'swiadomosc'),
  ('self-awareness', 'self-awareness'),
  ('eliminacja', 'eliminacja'),
  ('diversity', 'diversity'),
  ('inkluzja', 'inkluzja'),

  -- Well-being i BHP
  ('well-being', 'well-being'),
  ('stres', 'stres'),
  ('wypalenie zawodowe', 'wypalenie-zawodowe'),
  ('zdrowie psychiczne', 'zdrowie-psychiczne'),
  ('ergonomia', 'ergonomia'),
  ('work-life balance', 'work-life-balance'),
  ('praca zdalna', 'praca-zdalna'),
  ('elastyczność', 'elastycznosc'),
  ('remote work', 'remote-work'),
  ('zespoły zdalne', 'zespoly-zdalne'),
  ('virtual leadership', 'virtual-leadership'),
  ('współpraca', 'wspolpraca'),
  ('wellness', 'wellness'),
  ('programy zdrowotne', 'programy-zdrowotne'),
  ('workplace', 'workplace'),
  ('mental health', 'mental-health'),
  ('wsparcie psychologiczne', 'wsparcie-psychologiczne'),
  ('EAP', 'eap'),
  ('destygmatyzacja', 'destygmatyzacja'),
  ('otwartość', 'otwartosc'),
  ('stanowiska biurowe', 'stanowiska-biurowa'),
  ('audyty', 'audyty'),
  ('meble', 'meble'),
  ('edukacja', 'edukacja'),
  ('bezpieczeństwo', 'bezpieczenstwo'),
  ('ryzyko zawodowe', 'ryzyko-zawodowe'),
  ('kultura bezpieczeństwa', 'kultura-bezpieczenstwa'),
  ('procedury', 'procedury'),
  ('zdrowie', 'zdrowie'),
  ('stanowiska pracy', 'stanowiska-pracy'),
  ('diagnoza', 'diagnoza'),
  ('prewencja', 'prewencja'),
  ('odporność', 'odpornosc'),
  ('wsparcie', 'wsparcie'),

  -- HR Analytics i metryki
  ('HR analytics', 'hr-analytics'),
  ('KPI', 'kpi'),
  ('OKR', 'okr'),
  ('dashboardy', 'dashboardy'),
  ('metryki', 'metryki'),
  ('raportowanie', 'raportowanie'),
  ('dane', 'dane'),
  ('wskaźniki', 'wskazniki'),
  ('analytics', 'analytics'),
  ('data-driven HR', 'data-driven-hr'),
  ('workforce analytics', 'workforce-analytics'),
  ('predictive analytics', 'predictive-analytics'),
  ('people analytics', 'people-analytics'),
  ('HR metrics', 'hr-metrics'),

  -- Technologie i automatyzacja
  ('automatyzacja', 'automatyzacja'),
  ('HR tech', 'hr-tech'),
  ('RPA', 'rpa'),
  ('procesy', 'procesy'),
  ('digitalizacja', 'digitalizacja'),
  ('HR transformation', 'hr-transformation'),
  ('HRIS', 'hris'),
  ('change management', 'change-management'),
  ('machine learning', 'machine-learning'),
  ('chatboty', 'chatboty'),
  ('systemy rekrutacyjne', 'systemy-rekrutacyjne'),
  ('implementacja', 'implementacja'),
  ('optymalizacja', 'optymalizacja'),
  ('ROI', 'roi'),
  ('technologia', 'technologia'),
  ('IT', 'it'),

  -- Praca zdalna i hybrydowa
  ('hybrydowa praca', 'hybrid-work'),
  ('performance management', 'performance-management'),
  ('cele', 'cele'),

  -- Przyszłość i trendy
  ('future of work', 'future-of-work'),
  ('przyszłość', 'przyszlosc'),
  ('trendy', 'trendy'),
  ('transformacja', 'transformacja'),
  ('agile', 'agile'),
  ('competencies', 'competencies'),
  ('future skills', 'future-skills'),
  ('megatrends', 'megatrends'),
  ('scenario planning', 'scenario-planning'),
  ('foresight', 'foresight'),

  -- Specjalistyczne i branżowe
  ('HR business partner', 'hr-business-partner'),
  ('journey', 'journey')
ON CONFLICT (slug) DO NOTHING;


